# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
kernel <- function(x, krnl_type) {
    .Call('_mypac_kernel', PACKAGE = 'mypac', x, krnl_type)
}

#' @export
getBeta0 <- function(X, Y, w) {
    .Call('_mypac_getBeta0', PACKAGE = 'mypac', X, Y, w)
}

#' @export
ifelseYt <- function(x, num) {
    .Call('_mypac_ifelseYt', PACKAGE = 'mypac', x, num)
}

#' @export
ifelseNt <- function(x, delta1, num) {
    .Call('_mypac_ifelseNt', PACKAGE = 'mypac', x, delta1, num)
}

#' @export
bw_RT_bool <- function(x, y, krnl, deg) {
    .Call('_mypac_bw_RT_bool', PACKAGE = 'mypac', x, y, krnl, deg)
}

#' @export
bw_RT <- function(x, y, krnl, deg) {
    .Call('_mypac_bw_RT', PACKAGE = 'mypac', x, y, krnl, deg)
}

#' @export
est_h <- function(data, krnl, S_s, T1_s) {
    .Call('_mypac_est_h', PACKAGE = 'mypac', data, krnl, S_s, T1_s)
}

#' @export
Lambda_given_s <- function(S_s, T1_s, est_int1) {
    .Call('_mypac_Lambda_given_s', PACKAGE = 'mypac', S_s, T1_s, est_int1)
}

#' @export
final_CIF <- function(Surv_given_s, T1_s, dval) {
    .Call('_mypac_final_CIF', PACKAGE = 'mypac', Surv_given_s, T1_s, dval)
}

#' @export
new_CIF1 <- function(data, krnl, S_s, T1_s) {
    .Call('_mypac_new_CIF1', PACKAGE = 'mypac', data, krnl, S_s, T1_s)
}

rcpparma_hello_world <- function() {
    .Call('_mypac_rcpparma_hello_world', PACKAGE = 'mypac')
}

rcpparma_outerproduct <- function(x) {
    .Call('_mypac_rcpparma_outerproduct', PACKAGE = 'mypac', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_mypac_rcpparma_innerproduct', PACKAGE = 'mypac', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_mypac_rcpparma_bothproducts', PACKAGE = 'mypac', x)
}

